import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent, type MouseEvent, type ReactNode } from 'react'
import { GATEWAY_MODE, IS_DEMO_MODE, featureFlags } from './config'
import { fepGateway, getLocalDrafts, rewardsGateway } from './gateway'
import { activityItems, catalog, dreamStories, events, feedItems, groups, nearbyHelp, suggestedDreamImages, topics } from './data'
import type { AccountView, AppTab, CreateFlow, DiscoverView, LocalDraft, RequestCategory } from './types'

type IconName = 'home' | 'search' | 'plus' | 'bell' | 'user' | 'map' | 'arrow' | 'heart' | 'shield' | 'gift' | 'sparkles' | 'camera' | 'upload' | 'check' | 'close' | 'message' | 'calendar' | 'lock' | 'basket'
type Notice = { title: string; body: string } | null

const tabs: Array<{ id: AppTab; label: string; icon: IconName }> = [
  { id: 'home', label: 'Home', icon: 'home' },
  { id: 'discover', label: 'Discover', icon: 'search' },
  { id: 'create', label: 'Create', icon: 'plus' },
  { id: 'activity', label: 'Activity', icon: 'bell' },
  { id: 'you', label: 'You', icon: 'user' },
]

function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    home: <><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></>,
    plus: <><path d="M12 5v14"/><path d="M5 12h14"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
    user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, map: <><path d="M12 21s7-5 7-12a7 7 0 1 0-14 0c0 7 7 12 7 12Z"/><circle cx="12" cy="9" r="2"/></>,
    arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, heart: <path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>, gift: <><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M12 8v13M3 12h18"/></>,
    sparkles: <><path d="m12 3 1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/><path d="m19 14 .7 2.3L22 17l-2.3.7L19 20l-.7-2.3L16 17l2.3-.7L19 14Z"/></>,
    camera: <><path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="3"/></>, upload: <><path d="M12 16V4"/><path d="m7 9 5-5 5 5"/><path d="M5 20h14"/></>,
    check: <path d="m5 12 4 4L19 6"/>, close: <><path d="m6 6 12 12"/><path d="m18 6-12 12"/></>, message: <path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/></>, lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, basket: <><path d="m3 10 2 10h14l2-10Z"/><path d="m7 10 5-7 5 7"/></>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>
}

const money = (minor: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(minor / 100)
const DemoChip = () => <span className="demo-chip">{IS_DEMO_MODE ? 'Demo data' : GATEWAY_MODE}</span>
const Status = ({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) => <span className={`status-chip status-${tone}`}>{children}</span>
const Button = ({ children, onClick, disabled, variant = 'primary', type = 'button' }: { children: ReactNode; onClick?: () => void; disabled?: boolean; variant?: string; type?: 'button' | 'submit' }) => <button type={type} className={`button button-${variant}`} onClick={onClick} disabled={disabled}>{children}</button>
const Header = ({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) => <header className="app-header"><div><div className="brand-row"><span className="brand-word">{title}</span>{title === 'Bravvi' ? <DemoChip /> : null}</div>{subtitle ? <p>{subtitle}</p> : null}</div>{action}</header>
const SectionTitle = ({ children }: { children: ReactNode }) => <h2 className="section-title">{children}</h2>

function NoticeModal({ notice, close }: { notice: Notice; close: () => void }) {
  if (!notice) return null
  return <div className="modal-backdrop" onMouseDown={close}><section className="modal-card" role="dialog" aria-modal="true" onMouseDown={(event: MouseEvent<HTMLElement>) => event.stopPropagation()}><button className="icon-button modal-close" onClick={close}><Icon name="close"/></button><span className="modal-symbol"><Icon name="lock"/></span><h2>{notice.title}</h2><p>{notice.body}</p><Button onClick={close}>Understood</Button></section></div>
}

function Home({ go, notice }: { go: (tab: AppTab) => void; notice: (value: Notice) => void }) {
  return <div className="page"><Header title="Bravvi" subtitle="Good things, made easier to find." action={<button className="icon-button" onClick={() => go('activity')}><Icon name="bell"/></button>}/>
    <button className="location-row" onClick={() => notice({ title: 'Generalized location only', body: 'Exact addresses stay private until a separately authorized assignment or delivery workflow needs them.' })}><Icon name="map" size={16}/> Peninsula area <span>Change</span></button>
    <div className="title-row"><SectionTitle>Dreams</SectionTitle><button onClick={() => go('discover')}>See more</button></div>
    <div className="story-rail">{dreamStories.map((dream) => <button className="story-card" key={dream.id} onClick={() => notice({ title: dream.title, body: 'Following a dream does not allocate money or change essential-aid priority.' })}><img src={dream.image} alt=""/><span>{dream.state}</span><strong>{dream.title}</strong><small>{dream.region}</small></button>)}</div>
    <div className="filter-row"><button className="active">For you</button><button onClick={() => go('discover')}>Nearby</button><button onClick={() => go('discover')}>Community</button></div>
    <div className="feed-list">{feedItems.map((item) => <article className="feed-card" key={item.id}><div className="feed-head"><span className="avatar small">B</span><div><strong>{item.kind}</strong><small>{item.region}</small></div><Status tone={item.verified ? 'verified' : 'neutral'}>{item.verified ? 'Verified source' : 'Community'}</Status></div><img src={item.image} alt=""/><div className="feed-body"><Status tone={item.status === 'Reviewing' ? 'pending' : 'neutral'}>{item.status}</Status><h2>{item.title}</h2><p>{item.caption}</p><div className="feed-actions"><Button variant="secondary" onClick={() => notice({ title: 'Follow preview', body: 'No server-side follow was created in demo mode.' })}><Icon name="heart" size={17}/> Follow</Button><Button variant="quiet" onClick={() => notice({ title: 'Public-safe view', body: 'Private evidence, exact address, reward history and contact details are never part of a public card.' })}>View <Icon name="arrow" size={17}/></Button></div></div></article>)}</div>
  </div>
}

function Discover({ notice }: { notice: (value: Notice) => void }) {
  const [view, setView] = useState<DiscoverView>('nearby')
  const views: Array<[DiscoverView, string]> = [['nearby','Nearby help'],['groups','Groups'],['events','Events'],['topics','Topics']]
  return <div className="page"><Header title="Discover" subtitle="People, groups and useful things nearby."/><div className="segmented">{views.map(([id,label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}>{label}</button>)}</div>
    {view === 'nearby' ? <div className="stack"><Info icon="shield">V1 shows voluntary help only. Paid work and exact locations remain hidden.</Info>{nearbyHelp.map((item) => <Card key={item.id} icon="heart" title={item.title} meta={`${item.region} · ${item.time}`} detail={item.safety}><Button variant="secondary" onClick={() => notice({ title: 'Offer help preview', body: 'No assignment was created. A connected workflow must check account status, safety, consent and availability.' })}>Offer help</Button></Card>)}</div> : null}
    {view === 'groups' ? <div className="stack">{groups.map((item) => <Card key={item.id} avatar={item.name[0]} title={item.name} meta={`${item.members} members`} detail={item.topic}><Button variant="quiet" onClick={() => notice({ title: 'Group preview', body: featureFlags.groupJoining ? 'Join enabled.' : 'Joining remains hidden until authentication and moderation are connected.' })}>Open <Icon name="arrow" size={16}/></Button></Card>)}</div> : null}
    {view === 'events' ? <div className="stack">{events.map((item) => <Card key={item.id} icon="calendar" title={item.title} meta={`${item.when} · ${item.region}`} detail="Free event"><Button variant="secondary" onClick={() => notice({ title: 'Event preview', body: 'No RSVP was created. RSVP and attendance require connected account and safety controls.' })}>Details</Button></Card>)}</div> : null}
    {view === 'topics' ? <div className="stack"><Info icon="message">Topics preview the future Reddit-style layer. Realtime rooms remain disabled.</Info>{topics.map((item) => <button className="topic-row" key={item.id} onClick={() => notice({ title: item.title, body: 'Demo thread only. No message was posted.' })}><div><small>{item.group}</small><strong>{item.title}</strong><span>{item.replies} replies</span></div><Icon name="arrow"/></button>)}</div> : null}
  </div>
}

function Info({ icon, children }: { icon: IconName; children: ReactNode }) { return <div className="info"><Icon name={icon}/><p>{children}</p></div> }
function Card({ icon, avatar, title, meta, detail, children }: { icon?: IconName; avatar?: string; title: string; meta: string; detail: string; children: ReactNode }) { return <article className="list-card">{avatar ? <span className="avatar">{avatar}</span> : <span className="list-icon"><Icon name={icon ?? 'heart'}/></span>}<div><Status>{detail}</Status><h2>{title}</h2><p>{meta}</p></div>{children}</article> }

function Create({ saved, notice }: { saved: () => void; notice: (value: Notice) => void }) {
  const [flow, setFlow] = useState<CreateFlow>('menu')
  if (flow === 'request') return <RequestFlow back={() => setFlow('menu')} saved={saved}/>
  if (flow === 'offer') return <OfferFlow back={() => setFlow('menu')} saved={saved}/>
  if (flow === 'dream') return <DreamFlow back={() => setFlow('menu')} saved={saved}/>
  return <div className="page"><Header title="Create" subtitle="Start with what you want to do."/><div className="create-list"><CreateChoice icon="basket" title="Request help" body="Food, essentials and work equipment." onClick={() => setFlow('request')}/><CreateChoice icon="heart" title="Offer help" body="Share safe voluntary availability." onClick={() => setFlow('offer')}/><CreateChoice icon="sparkles" title="Share a dream" body="Prepare a private visual draft." onClick={() => setFlow('dream')}/></div><button className="safety-note" onClick={() => notice({ title: 'Emergency boundary', body: 'Bravvi is not an emergency dispatch service. Immediate danger requires local emergency services or an appropriate crisis resource.' })}><Icon name="shield" size={18}/> Immediate emergency? Bravvi cannot dispatch help. <Icon name="arrow" size={16}/></button></div>
}
function CreateChoice({ icon, title, body, onClick }: { icon: IconName; title: string; body: string; onClick: () => void }) { return <button className="create-choice" onClick={onClick}><span><Icon name={icon}/></span><div><strong>{title}</strong><p>{body}</p></div><Icon name="arrow"/></button> }
function FlowHeader({ title, back }: { title: string; back: () => void }) { return <div className="flow-header"><button onClick={back}>‹</button><h1>{title}</h1><DemoChip/></div> }

function RequestFlow({ back, saved }: { back: () => void; saved: () => void }) {
  const [category, setCategory] = useState<RequestCategory>('food'), [quantities, setQuantities] = useState<Record<string,number>>({}), [title, setTitle] = useState(''), [note, setNote] = useState(''), [review, setReview] = useState(false), [substitutionPolicy, setSubstitutionPolicy] = useState<'ask'|'similar'|'none'>('ask')
  const items = catalog[category], selected = items.filter((item) => (quantities[item.code] ?? 0) > 0).map((item) => ({ ...item, quantity: quantities[item.code] ?? 0 })), estimate = selected.reduce((sum,item) => sum + item.estimateMinor * item.quantity, 0)
  const change = (code: string, delta: number) => setQuantities((current) => ({ ...current, [code]: Math.max(0, (current[code] ?? 0) + delta) }))
  const save = async () => { await fepGateway.saveDraft({ id: crypto.randomUUID(), type: 'request', category, title: title.trim() || `${category} request`, note: note.trim(), items: selected, estimatedMinor: estimate, substitutionPolicy, status: 'LOCAL_DRAFT', createdAt: new Date().toISOString() }); saved() }
  return <div className="page"><FlowHeader title="Request help" back={back}/><div className="category-toggle"><button className={category === 'food' ? 'active' : ''} onClick={() => { setCategory('food'); setReview(false) }}>Food & essentials</button><button className={category === 'work' ? 'active' : ''} onClick={() => { setCategory('work'); setReview(false) }}>Work & equipment</button></div>{!review ? <><Field label="Request name"><input value={title} onChange={(e: ChangeEvent<HTMLInputElement>) => setTitle(e.target.value)} placeholder="What do you need?"/></Field><div className="catalog">{items.map((item) => <article key={item.code}><small>Estimated {money(item.estimateMinor)}</small><h3>{item.name}</h3><div><button onClick={() => change(item.code,-1)}>−</button><span>{quantities[item.code] ?? 0}</span><button onClick={() => change(item.code,1)}>+</button></div></article>)}</div><Field label="Important details"><textarea value={note} onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setNote(e.target.value)} rows={3} placeholder="Timing, household size, allergies or work requirement."/></Field><Field label="Substitutions"><select value={substitutionPolicy} onChange={(e: ChangeEvent<HTMLSelectElement>) => setSubstitutionPolicy(e.target.value as 'ask'|'similar'|'none')}><option value="ask">Ask before replacing</option><option value="similar">Similar approved item is okay</option><option value="none">Do not substitute</option></select></Field><div className="sticky-review"><div><small>Current estimate</small><strong>{money(estimate)}</strong></div><Button disabled={!selected.length} onClick={() => setReview(true)}>Review draft</Button></div></> : <div className="review"><Status tone="demo">Local draft only</Status><h2>{title || `${category} request`}</h2>{selected.map((item) => <div className="review-line" key={item.code}><span>{item.quantity} × {item.name}</span><strong>{money(item.estimateMinor * item.quantity)}</strong></div>)}<div className="review-total"><span>Estimated basket</span><strong>{money(estimate)}</strong></div><p>Prices are planning estimates, not vendor quotes. FEP would compare fresh approved vendor offers, fees, substitutions, delivery windows and the authorized amount.</p><div className="two-actions"><Button variant="secondary" onClick={() => setReview(false)}>Edit</Button><Button onClick={save}>Save on this device</Button></div></div>}</div>
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }

function OfferFlow({ back, saved }: { back: () => void; saved: () => void }) {
  const options = ['Moving a small item','Grocery pickup','Event help','Mentoring','Technology setup']; const [selected,setSelected] = useState<string[]>([]), [region,setRegion] = useState('Peninsula area'), [availability,setAvailability] = useState('Weekends')
  const toggle = (value: string) => setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current,value])
  const save = async () => { await fepGateway.saveDraft({ id: crypto.randomUUID(), type: 'offer', categories: selected, region, availability, status: 'LOCAL_DRAFT', createdAt: new Date().toISOString() }); saved() }
  return <div className="page"><FlowHeader title="Offer help" back={back}/><Info icon="shield">This is a voluntary availability draft, not employment, an assignment or a safety guarantee.</Info><Field label="What could you help with?"><div className="pills">{options.map((item) => <button key={item} className={selected.includes(item) ? 'active' : ''} onClick={() => toggle(item)}>{item}</button>)}</div></Field><Field label="General area"><input value={region} onChange={(e: ChangeEvent<HTMLInputElement>) => setRegion(e.target.value)}/></Field><Field label="Typical availability"><select value={availability} onChange={(e: ChangeEvent<HTMLSelectElement>) => setAvailability(e.target.value)}><option>Weekends</option><option>Weekday evenings</option><option>Weekday daytime</option><option>Varies</option></select></Field><Button disabled={!selected.length} onClick={save}>Save availability draft</Button></div>
}

function DreamFlow({ back, saved }: { back: () => void; saved: () => void }) {
  const [title,setTitle] = useState(''), [story,setStory] = useState(''), [imageUrl,setImageUrl] = useState(suggestedDreamImages[0]), [source,setSource] = useState<'upload-preview'|'suggested'|'ai-preview'>('suggested'); const input = useRef<HTMLInputElement|null>(null)
  const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === 'string') { setImageUrl(reader.result); setSource('upload-preview') } }; reader.readAsDataURL(file) }
  const save = async () => { await fepGateway.saveDraft({ id: crypto.randomUUID(), type: 'dream', title: title.trim(), story: story.trim(), imageUrl, imageSource: source, status: 'LOCAL_DRAFT', createdAt: new Date().toISOString() }); saved() }
  return <div className="page"><FlowHeader title="Share a dream" back={back}/><img className="dream-preview" src={imageUrl} alt="Selected dream visual preview"/><div className="media-actions"><button onClick={() => input.current?.click()}><Icon name="upload"/>Upload photo</button><button onClick={() => { setImageUrl(suggestedDreamImages[(suggestedDreamImages.indexOf(imageUrl)+1)%suggestedDreamImages.length]); setSource('suggested') }}><Icon name="camera"/>Suggested</button><button onClick={() => { setImageUrl(suggestedDreamImages[2]); setSource('ai-preview') }}><Icon name="sparkles"/>AI preview</button><input ref={input} hidden type="file" accept="image/*" onChange={(e: ChangeEvent<HTMLInputElement>) => upload(e.target.files?.[0])}/></div><p className="media-note"><Status tone="demo">{source}</Status> Confirm the visual before any future publishing request.</p><Field label="What is the dream?"><input value={title} onChange={(e: ChangeEvent<HTMLInputElement>) => setTitle(e.target.value)} placeholder="A laptop for coding school"/></Field><Field label="Why does it matter?"><textarea value={story} onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setStory(e.target.value)} rows={4}/></Field><Info icon="lock">Saving creates a private local draft. Publishing, moderation, consent and funding review are separate actions.</Info><Button disabled={!title.trim() || !story.trim()} onClick={save}>Save dream draft</Button></div>
}

function Activity({ rewards }: { rewards: () => void }) {
  const grouped = useMemo(() => ['Today','Earlier'].map((group) => ({ group, items: activityItems.filter((item) => item.group === group) })),[])
  return <div className="page"><Header title="Activity" subtitle="Verified updates, pending work and things that need you."/><button className="reward-link" onClick={rewards}><span><Icon name="gift"/></span><div><strong>Rewards activity</strong><p>Available, pending and reserved stay separate.</p></div><Icon name="arrow"/></button>{grouped.map(({group,items}) => <section key={group}><SectionTitle>{group}</SectionTitle><div className="activity-list">{items.map((item) => <article key={item.id}><span className={`dot tone-${item.tone}`}/><div><Status tone={item.tone}>{item.tone === 'action' ? 'Action needed' : item.tone}</Status><h2>{item.title}</h2><p>{item.detail}</p></div></article>)}</div></section>)}</div>
}

function You({ view, setView, notice }: { view: AccountView; setView: (view: AccountView) => void; notice: (value: Notice) => void }) {
  const drafts = getLocalDrafts()
  if (view === 'rewards') return <Rewards back={() => setView('home')} notice={notice}/>
  if (view !== 'home') return <AccountDetail view={view} drafts={drafts} back={() => setView('home')} notice={notice}/>
  return <div className="page"><Header title="You" action={<DemoChip/>}/><section className="profile"><span className="avatar large">CS</span><div><h1>Connor</h1><p><Icon name="map" size={14}/> Peninsula area</p></div><Button variant="secondary" onClick={() => notice({ title: 'Profile preview', body: 'Editing requires connected authentication. Exact address and sensitive case information are not part of the social profile.' })}>Edit</Button></section><div className="account-menu"><Menu icon="basket" title="My requests" detail={`${drafts.filter((item) => item.type === 'request').length} local drafts`} onClick={() => setView('requests')}/><Menu icon="gift" title="Rewards" detail="Demo balance and goals" onClick={() => setView('rewards')}/><Menu icon="heart" title="Community activity" detail="Volunteering and gratitude" onClick={() => setView('community')}/><Menu icon="shield" title="Privacy & safety" detail="Consent and visibility" onClick={() => setView('privacy')}/></div><section className="gratitude"><span><Icon name="heart"/></span><div><small>Kind words</small><blockquote>“Connor stayed patient and helped us carry the desk safely.”</blockquote><p>Community member · Demo preview</p></div></section><p className="boundary">No star rating, moral score, eligibility effect or public ranking is created from gratitude.</p></div>
}
function Menu({ icon,title,detail,onClick }: { icon: IconName; title: string; detail: string; onClick: () => void }) { return <button onClick={onClick}><span><Icon name={icon}/></span><div><strong>{title}</strong><small>{detail}</small></div><Icon name="arrow"/></button> }
function AccountDetail({ view,drafts,back,notice }: { view: Exclude<AccountView,'home'|'rewards'>; drafts: LocalDraft[]; back: () => void; notice: (value: Notice) => void }) { const titles = { requests:'My requests', community:'Community activity', privacy:'Privacy & safety' }; return <div className="page"><FlowHeader title={titles[view]} back={back}/>{view === 'requests' ? <div className="stack">{drafts.length ? drafts.map((draft) => <article className="draft" key={draft.id}><Status tone="demo">Saved on device</Status><h2>{draft.type === 'request' || draft.type === 'dream' ? draft.title : 'Volunteer availability'}</h2><p>{new Date(draft.createdAt).toLocaleString()}</p><small>Not submitted to FEP</small></article>) : <Empty title="No local drafts" body="Use Create to prepare a request, availability profile or dream."/>}</div> : null}{view === 'community' ? <><Info icon="heart">Connected participation will appear only after authenticated attributable events exist.</Info><Empty title="No connected activity" body="This preview does not fabricate joins, RSVPs or assignments."/></> : null}{view === 'privacy' ? <div className="stack"><Privacy title="Public profile" body="General name, avatar and broad location only"/><Privacy title="Public stories" body="Disabled until separate consent and moderation"/><Privacy title="Sponsor visibility" body="Aggregate impact only, never raw evidence or contact data"/><Button variant="secondary" onClick={() => notice({ title:'Consent model', body:'Consent must be versioned and able to unpublish dependent content without deleting private audit evidence.' })}>Review consent model</Button></div> : null}</div> }
function Privacy({ title,body }: { title:string; body:string }) { return <div className="privacy"><span><Icon name="lock"/></span><div><strong>{title}</strong><p>{body}</p></div><Status>Protected</Status></div> }
function Empty({ title,body }: { title:string; body:string }) { return <div className="empty"><Icon name="sparkles"/><h2>{title}</h2><p>{body}</p></div> }

function Rewards({ back, notice }: { back: () => void; notice: (value: Notice) => void }) {
  const [summary,setSummary] = useState<{availableMinor:number;pendingMinor:number;reservedMinor:number}|null>(null); useEffect(() => { rewardsGateway.getSummary().then(setSummary).catch(() => setSummary(null)) },[])
  const unavailable = (name:string) => notice({ title:`${name} is not active`, body:'No reward value moved. Live effects require the authoritative Rewards journal, identity, capability authorization and provider readback.' })
  return <div className="page"><FlowHeader title="Rewards" back={back}/><div className="wallet"><div><small>Available demo rewards</small><strong>{summary ? money(summary.availableMinor) : 'Unavailable'}</strong><DemoChip/></div><p>Available can be used by enabled programs. Pending is not settled. Reserved is held for a confirmed intent.</p><section><div><span>Pending</span><strong>{summary ? money(summary.pendingMinor) : '—'}</strong></div><div><span>Reserved</span><strong>{summary ? money(summary.reservedMinor) : '—'}</strong></div></section></div><div className="reward-actions"><Button variant="secondary" onClick={() => unavailable('Gifting')}>Gift</Button><Button variant="secondary" onClick={() => unavailable('Giving')}>Give</Button><Button variant="secondary" onClick={() => unavailable('Redemption')}>Redeem</Button></div><Info icon="shield">Reward balance, purchase history, giving behavior and goal activity are never used to decide aid eligibility or priority.</Info><SectionTitle>Goal</SectionTitle><article className="goal"><img src={suggestedDreamImages[1]} alt=""/><div><Status tone="demo">Demo goal</Status><h2>Family nature trip</h2><div className="progress"><span/></div><p>{money(51000)} of {money(150000)}</p></div></article><SectionTitle>How giving would work</SectionTitle><div className="protocol"><p><b>1</b> Rewards reserves confirmed units.</p><p><b>2</b> FEP validates a signed intent.</p><p><b>3</b> Acceptance captures; rejection or timeout releases.</p></div></div>
}

function Assistant({ open,close }: { open:boolean; close:() => void }) {
  const [question,setQuestion] = useState(''), [answer,setAnswer] = useState('I can explain this demo. I cannot approve support, reserve money, place an order or claim an action happened.')
  if (!open) return null
  const ask = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const text = question.toLowerCase(); setAnswer(text.includes('pending') ? 'Pending means the source event has not settled and the value is not available.' : text.includes('request') ? 'A private draft is not an approval. A real submission goes to FEP for evidence, policy and human review.' : text.includes('delivery') ? 'Only a current vendor or carrier readback can confirm delivery.' : 'No connected case snapshot is available, so I will not invent a status.'); setQuestion('') }
  return <div className="assistant-backdrop" onMouseDown={close}><section className="assistant" onMouseDown={(e: MouseEvent<HTMLElement>) => e.stopPropagation()}><div className="assistant-head"><span><Icon name="sparkles"/></span><div><strong>Ask Bravvi</strong><small>Local guidance demo</small></div><button className="icon-button" onClick={close}><Icon name="close"/></button></div><p>{answer}</p><form onSubmit={ask}><input value={question} onChange={(e: ChangeEvent<HTMLInputElement>) => setQuestion(e.target.value)} placeholder="Ask what a status means"/><button disabled={!question.trim()}><Icon name="arrow"/></button></form><small>No case data, reward journal or Sultan service is connected.</small></section></div>
}

function BottomNav({ active,change }: { active:AppTab; change:(tab:AppTab) => void }) { return <nav className="bottom-nav">{tabs.map((tab) => <button key={tab.id} className={active === tab.id ? 'active' : ''} onClick={() => change(tab.id)}><span className={tab.id === 'create' ? 'create-icon' : ''}><Icon name={tab.icon}/></span><small>{tab.label}</small></button>)}</nav> }

export default function App() {
  const [tab,setTab] = useState<AppTab>('home'), [accountView,setAccountView] = useState<AccountView>('home'), [notice,setNotice] = useState<Notice>(null), [assistant,setAssistant] = useState(false), [toast,setToast] = useState<string|null>(null)
  const go = (next:AppTab) => { setTab(next); if (next !== 'you') setAccountView('home'); window.scrollTo({top:0,behavior:'smooth'}) }
  const rewards = () => { setAccountView('rewards'); setTab('you'); window.scrollTo({top:0,behavior:'smooth'}) }
  const saved = () => { setToast('Draft saved on this device. Nothing was submitted to FEP.'); setTab('activity'); window.setTimeout(() => setToast(null),5000) }
  return <div className="app-shell"><main>{tab === 'home' ? <Home go={go} notice={setNotice}/> : null}{tab === 'discover' ? <Discover notice={setNotice}/> : null}{tab === 'create' ? <Create saved={saved} notice={setNotice}/> : null}{tab === 'activity' ? <Activity rewards={rewards}/> : null}{tab === 'you' ? <You view={accountView} setView={setAccountView} notice={setNotice}/> : null}</main><button className="assistant-fab" onClick={() => setAssistant(true)}><Icon name="sparkles"/></button><BottomNav active={tab} change={go}/><NoticeModal notice={notice} close={() => setNotice(null)}/><Assistant open={assistant} close={() => setAssistant(false)}/>{toast ? <div className="toast"><Icon name="check"/>{toast}</div> : null}</div>
}
